name: baku_chat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_core: ^1.6.0
  google_sign_in: ^5.0.7
  get: ^4.3.8
  firebase_auth: ^3.1.0
  lottie: ^1.1.0
  introduction_screen: ^2.1.0
  avatar_glow: 2.0.1
  emoji_picker_flutter: 1.0.7
  get_storage: 2.0.3
  cloud_firestore: 2.5.1
  intl: 0.17.0
  image_picker: 0.8.4
  firebase_storage: 10.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/icon.png"

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
    - assets/models/
  uses-material-design: true

